name: Adds all issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    if: github.repository_owner == 'McPringle'
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/users/McPringle/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
